### ISSUE TITLE
v3.0

### ISSUE THREAD

**Issue by Ovyerus** [ClarityCafe/Sagiri#119]
For version 3, we will be simplifying the API to a more functional interface, a la `bent` and similar libraries. This is because our library only does one thing - fetching data from SauceNAO - so this would greatly simplify our API.

Current usage
```js
const client = new Sagiri('...');
const resultss = await client.getSource('...');
```

Proposed changes
```js
const client = sagiri('token'); // Previous class becomes a function which returns a new async function to call
const results = await client('url');
```

We would also bring in the ability to override preset options when calling the new function, allowing to easily only enable options for some searches, such as fetching ratings or masks.

Another thing to introduce for v3 would be proper error handling and actually giving users the error message provided by SauceNAO, `SagiriClientError` and `SagiriServerError` both inheriting from `SagiriError` instead of throwing generic `Error` objects so users can actually do stuff depending on what happened.

One last thing to consider is whether we should just drop support for fetching ratings, as this is very janky and means we have to search through HTML most of the time, which can easily be broken, as did happen with SauceNAO. Perhaps we should replace this with a hard-coded boolean for indexes on whether or not the site is most likely NSFW? (cc @sr229)

- [x] Switch from a class to a simple functional API
- [x] Add better errors
- [x] Debug logging for better error triaging in the future
- [ ] Reintroduce a better method for ratings at some point in the future.
- [ ] Update documentation

**Comment by Ovyerus** [comment]
We should also add a mode for debug logging which can be enabled to see what's going on while it's working.

**Comment by sr229** [comment]
The thing is I've seen implementations using ratings so I don't think we should drop it considering we have a significant user base using ratings as well AFAIK. We'll support it until we do a little bit of survey to know if they actually use it.

**Comment by Ovyerus** [comment]
My main issue is the implementation of them, which is super janky and relies on sites not doing a redesign, but also most of the sites don't even have a proper check, just a forced always yes or no result anyway.

If users really want to check if a image is fine before posting, they can spin up their own solution that'd probably end up being more effective than our stuff, unless we integrated such a solution into the library ourselves.

**Comment by sr229** [comment]
I think its better we incorporate it in the lib since they use it as well in the first place.

**Comment by Ovyerus** [comment]
Could leave it out of 3.0 as a breaking change and then reintroduce it later in 3.1 once it's figured out.

**Comment by sr229** [comment]
LGTM
