### ISSUE TITLE
DeviantArt URLs not working with mask

### ISSUE THREAD

**Issue by Kotosif** [ClarityCafe/Sagiri#287]
URL is now something like this https://www.deviantart.com/rotix102/art/Dark-Magician-Girl-857559594
The site regex in sites.ts needs to be updated

**Comment by Kotosif** [comment]
Actually I see the URL SauceNao returns does look similar but it doesn't work with the mask

**Comment by sr229** [comment]
@Ovyerus

**Comment by sr229** [comment]
I'll be closing this now as part of housekeeping, let me know if this is still a bug that you encounter.
