### ISSUE TITLE
It ignores absolutely all options

### ISSUE THREAD

**Issue by mytecor** [ClarityCafe/Sagiri#288]
```js
import sagiri from 'sagiri'

let sauce = sagiri(process.env.SAUCE_TOKEN, {
  results: 1,
  mask: [5]
})

sauce(file).then(console.log)
```

Sagiri returns a large list of images from various sources

- version: 3.1.1
- Node.js version: 15.2.0
- Operating system: Win 10 Pro 20H2

**Comment by SlavyanDesu** [comment]
> ```js
> import sagiri from 'sagiri'
> 
> let sauce = sagiri(process.env.SAUCE_TOKEN, {
>   results: 1,
>   mask: [5]
> })
> 
> sauce(file).then(console.log)
> ```
> 
> Sagiri returns a large list of images from various sources
> 
> * version: 3.1.1
> * Node.js version: 15.2.0
> * Operating system: Win 10 Pro 20H2

Same issue here. But it seems `mask` option is working but not for `results`.
![image](https://user-images.githubusercontent.com/28254882/100717725-063f2780-33ed-11eb-82c6-ee0909e387fb.png)

**Comment by sr229** [comment]
That's weird, our test case would usually capture this kind of bug since we tested them.

**Comment by sr229** [comment]
I don't know if you still encounter this issue but I will be closing this as part of housekeeping. Please re-open a new one if you feel this is still an active issue.
