### ISSUE TITLE
No matter how, it always returns 5 results.

### ISSUE THREAD

**Issue by dimactavishy** [ClarityCafe/Sagiri#295]
```js
let amount = args.join( );

mySauce(imageurl, { results: amount })
                    .then(async response => {
                        console.log(response);
}

```
Sagiri keeps returning 5 results no matter what number i put in the `results`
Edit: Turns out 5 is the default number for it and i can change it from there, but i want the result amount to depend on what the bot user inputs. 
Another problem was that Heroku automatically installs `node_modules` on it's own so even if i change it, it will just revert back to 5.

- version: 3.1.1
- Node.js version: 16.13.0
- Operating system: Heroku (runs on LInux)
- Discord.js version: 12.5.3

**Comment by sr229** [comment]
I'm no longer seeing this bug so please let me know if this still persists.
