### ISSUE TITLE
Library throws warning for missing author ID 15

### ISSUE THREAD

**Issue by sr229** [ClarityCafe/Sagiri#297]
Right now there's an error that author ID 15 is missing, going to have to update index again and see if we can get ID 15

**Comment by AgentRBY** [comment]
The SauceNao site says that the 15 index is disabled. I haven't found any images that return a 15 index, so I'm not sure if this issue is relevant
![image](https://user-images.githubusercontent.com/68181944/223146472-f77f8c88-63f6-4d17-84e7-c545c0d677ae.png)

**Comment by sr229** [comment]
> The SauceNao site says that the 15 index is disabled. I haven't found any images that return a 15 index, so I'm not sure if this issue is relevant ![image](https://user-images.githubusercontent.com/68181944/223146472-f77f8c88-63f6-4d17-84e7-c545c0d677ae.png)

Probably worth to still index it locally so it doesn't throw an error.

**Comment by sr229** [comment]
After a bit of time I think I'll close this since this is intentionally broken.
