### ISSUE TITLE
URLs are determined by index

### ISSUE THREAD

**Issue by bobobo1618** [ClarityCafe/Sagiri#32]
Currently, the index a result came from is used [to determine which URL to return](https://github.com/ClarityCafe/Sagiri/blob/master/lib/Handler.js#L194-L195).

This can be problematic because for example, many Danbooru results are in the Gelbooru index, which results in Gelbooru URLs being returned. This is less helpful when determining sources because Gelbooru lacks all the tags of Danbooru as well as Danbooru's artist pages, which can link to their online profiles.

Instead, I propose that you keep an ordered mapping of `_id` fields to indexes/URLs, like so:

```javascript
[
  ["pixiv_id", pixiv],
  ["danbooru_id", danbooru],
  ["gelbooru_id", gelbooru]
]
```

Which can be used something like this:

```javascript
for (let index of Constants.indexes) {
  if (result[index[0]] != undefined) {
    url = index[1].makeUrl(result);
  }
}
```
Some sources don't have `_id` fields, so for those you can use the existing index matching.

**Comment by sr229** [comment]
CC @Ovyerus

**Comment by sr229** [comment]
How does this exactly impact the users of this library @bobobo1618? It seems a slight oversight from us it should be trivial.

**Comment by bobobo1618** [comment]
@sr229 the impact is that for results that return multiple boorus, only one booru will be returned in search results and from my understanding, that booru will more often than not be Gelbooru.

**Comment by sr229** [comment]
I'll be happy to accept a PR regarding this, but it seems to be also at fault in the SauceNAO side.

**Comment by sr229** [comment]
I'll be closing this issue for now since I think the effect is not really critical. Let us know if this is a really serious issue.
