### ISSUE TITLE
Library throws warning for missing author ID 38

### ISSUE THREAD

**Issue by ChinHongTan** [ClarityCafe/Sagiri#380]
**Please describe the problem you are having in as much detail as possible:**
So it warns me and asked me to inform the author.
And this might help a little?
```
    header: {
      similarity: '39.11',
      thumbnail: 'https://img3.saucenao.com/ehentai/3a/ac/3aac39b36d5ca4a395a8064d09f17ba6102b244a.jpg?auth=pfD2uJ-7KmssGLe67hT2cQ&exp=1667937600',
      index_id: 38,
      index_name: 'Index #38: H-Misc (E-Hentai) - 3aac39b36d5ca4a395a8064d09f17ba6102b244a.jpg',
      dupes: 0,
      hidden: 0
    },
```
**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by sr229** [comment]
I'll have to check ID 38 if it's already supported before adding it.

**Comment by sr229** [comment]
38 is not supported. Resolving.
